### ISSUE TITLE
Lodash repeat should be fed with a string, not a number

### ISSUE THREAD

**Issue by klimashkin** [beaugunderson/ip-address#85] opened 2019-04-11 18:04 UTC
We are using [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) to avoid including the whole lodash library in our bundle. 
And we faced with pretty subtle bug when `new Address4('10.0.10.0/24').startAddress().address` returning `0.10.0.10`.

After some debugging we found out that `ip-address` calls [`repeat`](https://lodash.com/docs/4.17.11#repeat) function from lodash with a number as a first argument, when it supposed to be string.
Full lodash transforms types by default, but with lodash-webpack-plugin it's not included by default.

For now, we're adding `coercions: true` option to plugin, but I think `ip-address` should fix `repeat` helper call to conform to its arguments typing, and to safe other developers from shooting themselves in their feet.

**Comment by beaugunderson** [comment] 2019-06-05 18:35
@klimashkin fixed in 5.9.2, thanks for your patience :)

(and as an aside: i know of no surer way to shoot yourself in the foot than to use lodash-webpack-plugin; it was the cause of no fewer than 5 subtle issues for us before we removed it)

**Closed** 2019-06-05 18:34 UTC
